import {
  AwsLogo,
  KubernetesLogo,
  ScopdLogo,
  AbuseIPDBLogo,
  CriminalIPLogo,
  DockerLogo,
  GoogleCloudLogo,
  JiraLogo,
  MaltiverseLogo,
  MicrosoftAzureLogo,
  MicrosoftTeamsLogo,
  VirusTotalLogo,
  MISPLogo,
  PagerDutyLogo,
  ServiceNowLogo,
  ShuffleLogo,
  SlackLogo,
  SplunkLogo,
  TheHiveLogo,
  TinesLogo, JuniperNetworksLogo, PanoAltoNetworksLogo, FortiNetLogo,
  CustomDeviceLogo,
  PfSenseLogo,
  KerioControlLogo,
  WindowsServerLogo,
  MicrosoftActiveDirectoryLogo,
  LinuxLogo,
  VmwareEsxiLogo,
  VmwareVcenterLogo,
  MicrosoftHyperVLogo,
  ProxmoxLogo,
  NginxLogo,
  ApacheLogo,
  ZabbixLogo,
  SafeticaDlpLogo,
  ScopdDlpLogo,
  Bitrix24Logo,
  OneCPlatformLogo,
  MicrosoftSqlServerLogo,
  PostgresqlLogo,
  OracleLogo,
  MysqlLogo,
  EsetLogo,
  DrWebLogo,
  HpeIloLogo,
  DellIdracLogo,
} from './logos';
import {CiscoLogo} from "./logos/CiscoLogo";

export const integrationIcons = {
  scopd: ScopdLogo,
  virusTotal: VirusTotalLogo,
  kubernetes: KubernetesLogo,
  aws: AwsLogo,
  abuseIpdb: AbuseIPDBLogo,
  criminalIp: CriminalIPLogo,
  docker: DockerLogo,
  googlecloud: GoogleCloudLogo,
  jira: JiraLogo,
  maltiverse: MaltiverseLogo,
  microsoftAzure: MicrosoftAzureLogo,
  microsoftTeams: MicrosoftTeamsLogo,
  misp: MISPLogo,
  pagerDuty: PagerDutyLogo,
  serviceNow: ServiceNowLogo,
  shuffle: ShuffleLogo,
  slack: SlackLogo,
  splunk: SplunkLogo,
  theHive: TheHiveLogo,
  tines: TinesLogo,
  juniperNetworks: JuniperNetworksLogo,
  cisco: CiscoLogo,
  panoAltoNetworks: PanoAltoNetworksLogo,
  fortiNet: FortiNetLogo,
  customDevice: CustomDeviceLogo,
  pfSense: PfSenseLogo,
  kerioControl: KerioControlLogo,
  windowsServer: WindowsServerLogo,
  microsoftActiveDirectory: MicrosoftActiveDirectoryLogo,
  linux: LinuxLogo,
  vmwareEsxi: VmwareEsxiLogo,
  vmwareVcenter: VmwareVcenterLogo,
  microsoftHyperV: MicrosoftHyperVLogo,
  proxmox: ProxmoxLogo,
  nginx: NginxLogo,
  apache: ApacheLogo,
  zabbix: ZabbixLogo,
  safeticaDlp: SafeticaDlpLogo,
  scopdDlp: ScopdLogo,
  bitrix24: Bitrix24Logo,
  oneCPlatform: OneCPlatformLogo,
  microsoftSqlServer: MicrosoftSqlServerLogo,
  postgresql: PostgresqlLogo,
  oracle: OracleLogo,
  mysql: MysqlLogo,
  eset: EsetLogo,
  drWeb: DrWebLogo,
  hpeIlo: HpeIloLogo,
  dellIdrac: DellIdracLogo,
} as const;

export type IntegrationIconName = keyof typeof integrationIcons;
