import {
  AwsLogo,
  KubernetesLogo,
  ScopdLogo,
  AbuseIPDBLogo,
  CriminalIPLogo,
  DockerLogo,
  GoogleCloudLogo,
  JiraLogo,
  MaltiverseLogo,
  MicrosoftAzureLogo,
  MicrosoftTeamsLogo,
  VirusTotalLogo,
  MISPLogo,
  PagerDutyLogo,
  ServiceNowLogo,
  ShuffleLogo,
  SlackLogo,
  SplunkLogo,
  TheHiveLogo,
  TinesLogo, JuniperNetworksLogo, PanoAltoNetworksLogo, FortiNetLogo,
  CustomDeviceLogo,
} from './logos';
import {CiscoLogo} from "./logos/CiscoLogo";

export const integrationIcons = {
  scopd: ScopdLogo,
  virusTotal: VirusTotalLogo,
  kubernetes: KubernetesLogo,
  aws: AwsLogo,
  abuseIpdb: AbuseIPDBLogo,
  criminalIp: CriminalIPLogo,
  docker: DockerLogo,
  googlecloud: GoogleCloudLogo,
  jira: JiraLogo,
  maltiverse: MaltiverseLogo,
  microsoftAzure: MicrosoftAzureLogo,
  microsoftTeams: MicrosoftTeamsLogo,
  misp: MISPLogo,
  pagerDuty: PagerDutyLogo,
  serviceNow: ServiceNowLogo,
  shuffle: ShuffleLogo,
  slack: SlackLogo,
  splunk: SplunkLogo,
  theHive: TheHiveLogo,
  tines: TinesLogo,
  juniperNetworks: JuniperNetworksLogo,
  cisco: CiscoLogo,
  panoAltoNetworks: PanoAltoNetworksLogo,
  fortiNet: FortiNetLogo,
  customDevice: CustomDeviceLogo
} as const;

export type IntegrationIconName = keyof typeof integrationIcons;
